backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

display_url: https://codeforsanfrancisco.org
logo_url: https://codeforsanfrancisco.org/img/logo.png

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Featured image", name: "image", widget: "image"}
      - {label: "Featured image alt text", name: "image_alt", widget: "string"}
      - {label: "Post Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Short description", name: "description", widget: "string"}
      - {label: "Pin To Frontpage", name: "pin_to_frontpage", widget: "boolean"}
      - {label: "Only show image in listing", name: "image_list_only", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "projects"
    label: "Project"
    folder: "_projects"
    sort: "title:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Project Link", name: "app_link", widget: "string", }
      - {label: "License", name: "license", widget: "string"}
      - {label: "Slack Channel Name", name: "slack", widget: "string", required: false}
      - label: "Project Status"
        name: "project_status"
        widget: "select"
        options:
          - proposed
          - discovery
          - prototype
          - mvp
          - alpha
          - beta
          - live
          - production
        default: proposed
      - {label: "Project Image", name: "image_path", widget: "image"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Short Blurb", name: "blurb", widget: "string"}
      - {label: "Skills Needed", name: "skills_needed", widget: "list", required: false}
      - {label: "Related Civic Topics", name: "civic_topics", widget: "list", required: false}
      - {label: "Links to repositories", name: "repos", widget: "list", required: false}
      - {label: "Project Description", name: "body", widget: "markdown"}
